BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "ark"
BBFILE_PATTERN_ark = "^${LAYERDIR}/"
BBFILE_PRIORITY_ark = "10"
LAYERVERSION_ark = "1"
LAYERDEPENDS_ark = "core tegra openembedded-layer"
LAYERSERIES_COMPAT_ark = "wrynose"
