# SPDX-License-Identifier: MIT
# nvpower queues native power-policy udev events without waiting. Finish only
# the Orin GPU event before nvpower completes and its dependent nvpmodel runs.
# No power mode or mask is selected here; NVIDIA's configured policy applies.
[Unit]
Requires=systemd-modules-load.service systemd-udevd.service
After=systemd-udevd.service

[Service]
ExecStartPost=@SH@ -ec 'test -L /sys/devices/platform/bus@0/17000000.gpu/driver; exec @UDEVADM@ trigger --action=change --settle --subsystem-match=platform --sysname-match=17000000.gpu /sys/devices/platform/bus@0/17000000.gpu'
TimeoutStartSec=60
